// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsA3w2Vqyy0vi_T-Zh9vVhoO83Zl1SsWE',
    appId: '1:732296261393:web:153e800b35f5dbb56e66b0',
    messagingSenderId: '732296261393',
    projectId: 'app-bodega-497a5',
    authDomain: 'app-bodega-497a5.firebaseapp.com',
    storageBucket: 'app-bodega-497a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXbl99zl-S62b0H5UBB9OhvjOO9OS43f4',
    appId: '1:732296261393:android:3a685ff7674108396e66b0',
    messagingSenderId: '732296261393',
    projectId: 'app-bodega-497a5',
    storageBucket: 'app-bodega-497a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAazYWbCsO_-OYSNs8Wjmf0s2u-dEUDr5Y',
    appId: '1:732296261393:ios:0113df51540d1f676e66b0',
    messagingSenderId: '732296261393',
    projectId: 'app-bodega-497a5',
    storageBucket: 'app-bodega-497a5.firebasestorage.app',
    iosBundleId: 'com.example.laBodeguitaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAazYWbCsO_-OYSNs8Wjmf0s2u-dEUDr5Y',
    appId: '1:732296261393:ios:0113df51540d1f676e66b0',
    messagingSenderId: '732296261393',
    projectId: 'app-bodega-497a5',
    storageBucket: 'app-bodega-497a5.firebasestorage.app',
    iosBundleId: 'com.example.laBodeguitaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsA3w2Vqyy0vi_T-Zh9vVhoO83Zl1SsWE',
    appId: '1:732296261393:web:153e800b35f5dbb56e66b0',
    messagingSenderId: '732296261393',
    projectId: 'app-bodega-497a5',
    authDomain: 'app-bodega-497a5.firebaseapp.com',
    storageBucket: 'app-bodega-497a5.firebasestorage.app',
  );
}
